version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: odds-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: odds_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - odds-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: odds-postgres-data

networks:
  odds-network:
    name: odds-network 